### ISSUE TITLE
Support for complex bases

### ISSUE THREAD

**Issue by blegat** [kalmarek/SymbolicWedderburn.jl#20]
Implement `isotypical_basis` for complex numbers and add an option in `symmetry_adapted_basis` to choose between real and complex

**Comment by kalmarek** [comment]
should be addressed by
https://github.com/kalmarek/SymbolicWedderburn.jl/pull/15/commits/4026bedcf1e1232825135b062644ce449b33b7d6

I.e. you may write 
```julia
symmetry_adapted_basis(Complex{Rational{Int}}, G)
```
to obtain (possibly) complex, exact basis (well, as long as You don't overflow). Elements of each block will be `Cyclotomic{Rational{Int}, ...}`. On the other hand
```
symmetry_adapted_basis(Rational{Int}, G)
```
will give you real, exact basis, with conjugate subspaces merged together.
