### ISSUE TITLE
Further decompose isotypic component

### ISSUE THREAD

**Issue by blegat** [kalmarek/SymbolicWedderburn.jl#28]
If the degree `d` of the character is larger than 2, we can further decompose the isotypic component into `d` a direct sum of `d` sub-components.
This can further reduce the SDP as each of these `d` blocks are equal. Each block will have the dimension given by the corresponding entry in the `multiplicities` vector.

**Comment by kalmarek** [comment]
Indeed. Here: https://arxiv.org/pdf/1712.07167.pdf (page 13) we worked out the rank-one projections that produce the decomposition for `C₂ ≀ Sym(n)` for `n≤6`. This was done by restricting every character to small subgroup (by composing with the projection onto the characteristic function of the subgroup) and hoping that some of the small subgroups will give you `χ·p_H` of degree `1`. (this brute force search surprisingly works for all characters).  

 But I don't know how to do it in general (symbolically). I asked (back in 2017) a few experts  in the field (representations of finite group) and this seems to be an open problem.

**Comment by kalmarek** [comment]
partially solved by #38, closing for now
