### ISSUE TITLE
Non-orthogonal semisimple summand

### ISSUE THREAD

**Issue by blegat** [kalmarek/SymbolicWedderburn.jl#35]
With the group in https://gist.github.com/kalmarek/37fde1975162b9709f72d6a312fcbf91, the basis is
```
1 0 -1 0
0 1 -1 0
```
which gives the induced matrices
```
-1 -1
 1  0
```
and
```
 1  0
-1 -1
```
which are not orthogonal.
The SDP solution is
```
 2 -1
-1  2
```
which has eigenvalues `(1, 3)` and eigenvectors `(1, 1)` and `(1, -1)` so we guess a different basis
```
1  1 -2 0
1 -1  0 0
```
which has orthogonal induced matrices.
Would it be possible for SymbolicWedderburn to return this basis instead ?

**Comment by kalmarek** [comment]
orthogonal bases are not really possible with exact/symbolic numbers; for now if you specify `Float64` (or `Complex64`) as the first argument to `symmetry_adapted_basis` `svd` will be used to find an orthogonal basis, otherwise we keep it as is (see the docstring for `symmetry_adapted_basis`).
