### ISSUE TITLE
AssertionError: Use wider Integer type!

### ISSUE THREAD

**Issue by thinh-le** [kalmarek/SymbolicWedderburn.jl#45]
For a large scale problem
```
SymbolicWedderburn.WedderburnDecomposition(Float64, Hb, BySignedPermutation(), basis_full, basis_half, semisimple = false)
```
with `length(basis_half)=4114` and `length(basis_full)=4453030` defined with UInt32 index

```
basis_full = StarAlgebras.Basis{UInt32}(words)
```
gives the error in this call
```
SymbolicWedderburn.invariant_vectors(tbl, BySignedPermutation(), basis_full)
ERROR: AssertionError: Use wider Integer type!
```

This is because `InducedActionHomomorphism` has been internally fixed to UInt16 in actions.jl. Perhaps propagating type information in `StarAlgebras.Basis{UInt32}` to other parts of the package is better?

My manual fix of the error (on julia 1.7, SymbolicWedderburn#fix/symbolic_invariant_vectors):
```
_int_type(::InducedActionHomomorphism) = UInt32
ExtensionHomomorphism(ac::Action, features) =
    ExtensionHomomorphism{UInt32}(ac, features)
```

Of course, doing svd for such a large scale problem might be impossible.

**Comment by kalmarek** [comment]
This should be fixed by #44, if the issue persists please reopen
